version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t https://github.com/SaqibMehraj/Demo-app-nginx.git#main .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  name: testing-nginx
